# -*- coding: utf-8 -*-
"""node2vec-using.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2UexmWt7vpV1kGDjQMtqTslWRS5OEJa
"""

!pip install gensim

import networkx as nx
import random
import numpy as np
import matplotlib.pyplot as plt

from gensim.models.word2vec import Word2Vec
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

random.seed(0)
np.random.seed(0)

from io import BytesIO
from urllib.request import urlopen
from zipfile import ZipFile

url = 'https://files.grouplens.org/datasets/movielens/ml-100k.zip'

with urlopen(url) as zurl:
    with ZipFile(BytesIO(zurl.read())) as zfile:
        zfile.extractall('.')

import pandas as pd

ratings = pd.read_csv('ml-100k/u.data',
                     sep='\t',
                     names=['user_id', 'movie_id', 'rating', 'unix_timestamp'])

# Afișăm primele rânduri
ratings.head()

movies = pd.read_csv('ml-100k/u.item',
                     sep = '|',
                     usecols = range(2),
                     names=['movie_id', 'title'],
                    encoding='latin-1')
movies

ratings = ratings[ratings.rating >= 4]
ratings

from collections import defaultdict

pairs = defaultdict(int)

# Loop through the entire list of users
for group in ratings.groupby("user_id"):
    # List of IDs of movies rated by the current user
    user_movies = list(group[1]["movie_id"])

    # Count every time two movies are seen together
    for i in range(len(user_movies)):
        for j in range(i+1, len(user_movies)):
            pairs[(user_movies[i], user_movies[j])] += 1

G = nx.Graph()

# Try to create an edge between movies that are liked together
for pair in pairs:
    movie1, movie2 = pair
    score = pairs[pair]

    # The edge is only created when the score is high enough
    if score >= 20:
        G.add_edge(movie1, movie2, weight=score)

print("Total number of graph nodes:", G.number_of_nodes())
print("Total number of graph edges:", G.number_of_edges())

nx.draw(G, with_labels=True)

# Display the graph
plt.show()

!pip install node2vec

from node2vec import Node2Vec

node2vec = Node2Vec(G,
                    dimensions=64,
                    walk_length=20,
                    num_walks=200,
                    p=2,
                    q=1,
                    workers=1)

model = node2vec.fit(window=10, min_count=1, batch_words=4)

def recommend(movie):
    movie_id = str(movies[movies.title == movie].movie_id.values[0])
    for id in model.wv.most_similar(movie_id)[:10]:
        title = movies[movies.movie_id == int(id[0])].title.values[0]
        print(f'{title}: {id[1]:.2f}')

recommend('Star Wars (1977)')

recommend('Godfather, The (1972)')